name: Delete old workflow and packages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 14

      - name: Delete old package
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'mihomo'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: 'true'